FROM golang:1.25-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o registry ./cmd/registry

FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/registry .
EXPOSE 8090
CMD ["./registry"]
