services:
  loadbalancer:
    build: .
    ports:
      - "8080:8080"
      - "9091:9091"
    depends_on:
      - tempo
      - backend1
      - backend2
      - backend3
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - "./prometheus.yaml:/etc/prometheus/prometheus.yml"
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - "./grafana/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml"
  tempo:
    image: grafana/tempo:latest
    ports:
      - "3200:3200"
      - "4317:4317"
    volumes:
      - "./tempo.yaml:/etc/tempo.yaml"
    command: "-config.file=/etc/tempo.yaml"
  loki:
    image: "grafana/loki:latest"
    ports:
      - "3100:3100"
    volumes:
      - "./loki.yaml:/etc/loki/local-config.yaml"
  promtail:
    image: "grafana/promtail:latest"
    user: root
    volumes:
      - "/var/lib/docker/containers:/var/lib/docker/containers:ro"
      - "./promtail.yaml:/etc/promtail/config.yaml"
    command: "-config.file=/etc/promtail/config.yaml"
  backend1:
    build:
      context: .
      dockerfile: Dockerfile.backend
    command: ["./testbackend", "8081"]
    ports:
      - "8081:8081"
  backend2:
    build:
      context: .
      dockerfile: Dockerfile.backend
    command: ["./testbackend", "8082"]
    ports:
      - "8082:8082"
  backend3:
    build:
      context: .
      dockerfile: Dockerfile.backend
    command: ["./testbackend", "8083"]
    ports:
      - "8083:8083"
