FROM golang:1.25-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o testbackend ./cmd/testbackend

FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/testbackend .
EXPOSE 8081 8082 8083
CMD ["./testbackend"]
