services:
  loadbalancer:
    build: .
    network_mode: "host"
    depends_on:
      - tempo
    logging:
      driver: json-file
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - "./grafana/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml"
  tempo:
    image: grafana/tempo:latest
    ports:
      - "3200:3200"
      - "4317:4317"
    volumes:
      - "./tempo.yaml:/etc/tempo.yaml"
    command: "-config.file=/etc/tempo.yaml"
  loki:
    image: "grafana/loki:latest"
    ports:
      - "3100:3100"
    volumes:
      - "./loki.yaml:/etc/loki/local-config.yaml"
  promtail:
    image: "grafana/promtail:latest"
    user: root
    volumes:
      - "/var/lib/docker/containers:/var/lib/docker/containers:ro"
      - "./promtail.yaml:/etc/promtail/config.yaml"
    command: "-config.file=/etc/promtail/config.yaml"
